# DO NOT EDIT
#
# GENERATED BY: Inline::Module 0.27

use strict; use warnings;
package Devel::GlobalDestruction::XS::Inline;
use base 'DynaLoader';
bootstrap Devel::GlobalDestruction::XS::Inline;

1;
